name: Deploy Production
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Checkout Environment Repo
        uses: actions/checkout@v2
        with:
          repository: PhoenixDAO/phoenix-dao-api-environments.git
          ref: main
          token: ${{ secrets.PAT_GITHUB }}
          path: phoenix-env

      - name: Copy Environments From Config Repo
        run: |
          cp phoenix-env/dao_server.config .ebextensions/02_environment.config
          cp phoenix-env/dao_config.yml .elasticbeanstalk/config.yml
          
      - name: Generate deployment package
        run: zip -r application.zip * */* .sequelizerc .ebextensions/* .elasticbeanstalk/* .platform/* -x '*.git*' blocasset/*

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.APP_NAME }}
          environment_name: ${{ secrets.PROD_APP_ENVIRONMENT }}
          version_label: "phoenix-dao-server-${{ steps.format-time.outputs.replaced }}"
          region: ${{ secrets.AWS_REGION }}
          existing_bucket_name: ${{ secrets.AWS_S3_BUCKET }}
          deployment_package: application.zip
          wait_for_environment_recovery: 120
          wait_for_deployment: false